name: cvapps
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - cairo=1.18.4
  - contourpy=1.2.1
  - cycler=0.11.0
  - dav1d=1.2.1
  - eigen=3.4.0
  - expat=2.7.1
  - ffmpeg=6.1.1
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freeglut=3.4.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - gflags=2.2.2
  - glog=0.5.0
  - graphite2=1.3.14
  - gst-plugins-base=1.24.12
  - gstreamer=1.24.12
  - gstreamer-orc=0.4.41
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - icc_rt=2022.1.0
  - icu=73.1
  - importlib_resources=6.5.2
  - intel-openmp=2023.1.0
  - jpeg=9f
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.1.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.84.4
  - libiconv=1.16
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - libogg=1.3.5
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=5.29.3
  - libtheora=1.2.0
  - libtiff=4.7.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - numpy=2.0.2
  - numpy-base=2.0.2
  - opencv=4.12.0
  - openjpeg=2.5.4
  - openssl=3.0.18
  - packaging=25.0
  - pcre2=10.46
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - ply=3.11
  - pybind11-abi=5
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.9.24
  - python-dateutil=2.9.0post0
  - python_abi=3.9
  - qt-main=5.15.2
  - qtbase=6.9.2
  - scipy=1.13.1
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.17.0
  - sqlite=3.50.2
  - tbb=2021.8.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.1
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
prefix: C:\Users\yared\miniconda3\envs\cvapps
